### ISSUE TITLE
playing の重複に対し, エラーを表示する

### ISSUE THREAD

**Issue by rhinocerosSai** [sankichi92/LiveLog#115]
songs/{song_id}/edit で, 同じメンバーが二つ以上演奏しているとして登録すると, `Playings userはすでに存在します` とバリデーションエラーが表示されるが, 

- songs/new では, エラーが出ず落ちる.
- lives/{live_id}/entry/new では, Send ボタンを押しても何も起こらない.

**Comment by sankichi92** [comment]
Related: #27
