### ISSUE TITLE
PA メールのFrom 欄に, エントリーをしたメンバーの名前を表示する

### ISSUE THREAD

**Issue by rhinocerosSai** [sankichi92/LiveLog#116]
- PA メールのメール一覧で, 送信者がすべて `LiveLog<noreply@....>` となり, 管理しにくい
- 同じところから送っていると判断され, promotion フォルダに振り分けられてしまう

ようです.

**Comment by rhinocerosSai** [comment]
`SongMailer` の  `from` を `エントリーをしたメンバー名<noreply@...>` か `エントリーをしたメンバー名<メンバーのメールアドレス>`
とすると今まで通り管理できるかと思いますが,  `曲名<noreply@...>` とするとさらに管理しやすくなるかもしれません.

**Comment by sankichi92** [comment]
ヘッダーの `From` を `エントリーをしたメンバー名 <noreply@livelog.ku-unplugged.net>` にするのが一番筋がいいかなあと思います。

`エントリーをしたメンバー名 <メンバーのメールアドレス>` だと，送信元サーバーのドメイン名と `From` のメールアドレスのドメイン名が異なるため「なりすましメール」になり，迷惑メール扱いされる可能性が高くなります。また，`Reply-To` にはエントリーしたメンバーのメールアドレスを入れるようにしているので，対応しているメールクライアントであれば，`From` が LiveLog でも返信先はエントリーしたメンバーになるはずです。

`曲名<noreply@...>` は送信者を表す `From` ヘッダーに対して適切ではありません。`Subject` に曲名を入れているので，そちらを参照するべきです。

---

> 同じところから送っていると判断され, promotion フォルダに振り分けられてしまう

これに関しては，Gmail や Inbox 等のメールクライアントで適切なフィルタを設定してほしいですね……。
「`From` が `noreply@livelog.ku-unplugged.net` の場合は promotion フォルダに入れない」とか「`Subject` に `10月ライブ` を含む場合は `10月ライブ` ラベルをつける」みたいなフィルタを設定すれば，かなり楽に管理できるはずです。
