### ISSUE TITLE
`An admin user cannot create the song with duplicated players` のテストが Travis CI で時々コケる

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#134]

**Comment by rhinocerosSai** [comment]
根本的な解決策ではないですが, 手動でrebuild できるようになると助かります

**Comment by sankichi92** [comment]
<img width="1239" alt="2017-10-29 16 37 13" src="https://user-images.githubusercontent.com/6823454/32141586-79ddccbe-bcc7-11e7-8c3e-f8aaf110055d.png">

ちなみに，Collaborator でも右上の `Restart build` ボタンって出ないですか？（自分では確認できない……）
Collaborator にはこのボタン表示する設定とかあったりするのかな……。

**Comment by rhinocerosSai** [comment]
Travis にログインしたら`Restart build` ボタンが出るようになりました
ありがとうございます

**Comment by sankichi92** [comment]
👍

**Comment by sankichi92** [comment]
解決したように思ったけど，根本的な解決じゃなかった。

**Comment by sankichi92** [comment]
最近コケてない気がするのでいったんクローズ。
必要に応じてリオープンする。
