### ISSUE TITLE
[ご意見・ご要望] エントリーフォーム

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#137]
> エンターキーを二回押すと、曲提出申請データの編集途中でも送信されてしまう仕様は、誤送信の元だと思うので、改善お願いします！

**Comment by sankichi92** [comment]
確かに……。

**Comment by rhinocerosSai** [comment]
送信の前に, dialog を出せば誤送信は防げるでしょうか...?

**Comment by sankichi92** [comment]
あ，今その方向で修正してます🙏
