### ISSUE TITLE
ピアノシフトをログインユーザー向けにトップで表示する

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#143]
## 課題

ピアノシフトの確認が面倒である

## 解決策

ピアノシフトを LiveLog トップに表示する

1. ピアノシフトで「一般公開して誰でも利用できるようにする（閲覧権限）」設定をオンにする
2. ピアノシフトカレンダーを LiveLog トップに iframe で埋め込んで，ログインユーザーにのみ表示されるようにする

---

@rhinocerosSai ピアノシフトの予定自体は基本的に個人情報を含んでいないので，公開設定自体に問題ないのではと思っています。
もし可能だったらカレンダー ID を教えていただけると助かります🙏
不可であればこの Issue クローズしてください。

**Comment by rhinocerosSai** [comment]
LiveLogからピアノシフトを入れるのは難しいでしょうか....?

しばらく先であっても, 導入する可能性があるのであればAPI の方がいいですか?

**Comment by sankichi92** [comment]
LiveLog はその名の通り，ライブ関連の機能のみを扱う Web アプリケーションにしたいです。
あまり機能を増やすと運用も大変になるので，ピアノシフトの入力機能はあまり入れたくないですね…。

**Comment by sankichi92** [comment]
#161 の例会教室機能のクローズに伴ってこれも無しで
