### ISSUE TITLE
例会教室を Google カレンダーに保存する

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#144]
## 課題

LiveLog で例会教室を取得しているが，1日キャッシュするのみで保存しておらず，翌日の教室も確認できない

## 解決策

取得した例会教室情報を [Google Calendar API](https://developers.google.com/google-apps/calendar/quickstart/ruby) を使って Google カレンダーに保存し，カレンダーを LiveLog トップに表示する

**Comment by sankichi92** [comment]
そもそも例会教室を「魔法のiらんど」なんかじゃなく，Google カレンダー等データとして扱いやすい形で入力してほしい……

**Comment by rhinocerosSai** [comment]
魔法のiランドの更新がかなり手間だそうですので, これを期に変えるのもいいかと思います. 
Google Calendarでいいでしょうか...?

**Comment by sankichi92** [comment]
Google カレンダーが無難だけど，入力はそれほど楽じゃない気がする……。
ただ，他に選択肢もないので自分がやるとしたら以下のような運用かなあ。

1. `regular-meeting@ku-unplugged` アカウントを作る
2. そのアカウントで Google カレンダーに「例会教室」カレンダーを作る
3. 例会教室を編集できる人たちの Google アカウントに編集権限を渡す（ピアノシフトと同じ）
    - メインの管理者にはアカウントをそのまま渡しても良い
    - 例会教室の入力は，終日設定でタイトルに全情報を入れるようにする
4. 「一般公開して誰でも利用できるようにする（閲覧権限）」設定をオンにして，カレンダー ID や URL
 を全会員に共有，公式ページからもリンクを貼る

エンジニア的には，LiveLog とは別に例会教室入力補助アプリを作る選択肢もありだと思います（自分がやるつもりはないです）。

**Comment by sankichi92** [comment]
Google カレンダー化が実現したので，#155 に移動
