### ISSUE TITLE
例会教室の取り込み元を Google カレンダーに変更する

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#155]
Google Calendar: https://calendar.google.com/calendar/embed?src=meeting-room%40ku-unplugged.net&ctz=Asia%2FTokyo

**Comment by sankichi92** [comment]
@rhinocerosSai Google Calendar 化するならスマホでの確認も簡単になるし，LiveLog のトップで表示する必要ない気がしてきたのですが，実際どのくらいの人があれを見てるかとかわかりますか？

LiveLog を普段から使ってもらうために追加したものの，例会教室の表示は「ライブを管理する」という LiveLog の本来の目的と異なると個人的に思っていて，利用者が少ないようであれば機能ごと消してしまおうかと思っています。

**Comment by rhinocerosSai** [comment]
今は見ている, という声をよく聞きますが, カレンダーから確認できるのであればニーズは減るかと思います. 

 それと, 必要であれば LiveLogよりもホームページで実装すべきかとも思います...

**Comment by sankichi92** [comment]
> カレンダーから確認できるのであればニーズは減るかと思います.

そうですね。
実装も面倒なので，LiveLog の例会教室機能は12月でクローズします。

**Comment by sankichi92** [comment]
#161 へ移行
