### ISSUE TITLE
共演者の表示を改善する

### ISSUE THREAD

**Issue by rhinocerosSai** [sankichi92/LiveLog#261]
- 共演者を多い順に並べて表示する
- 各共演者について, 回数を表示する

**Comment by rhinocerosSai** [comment]
と思ったのですが, 同一回数の共演者が10人以上いても10人で打ち切るので, それならむしろ表示しない方が, という判断でしょうか...?

**Comment by sankichi92** [comment]
> 共演者を多い順に並べて表示する

確かに多い順になってない……。なんでだろう。
これは完全に意図してませんでした🙏

> 各共演者について, 回数を表示する

回数に表示するほどの価値がないと思ったので消しちゃいました。

> 0人で打ち切るので, それならむしろ表示しない方が

これもあります。

**Comment by rhinocerosSai** [comment]
`collaborators` の, User.where(id:....` で,順番が保持されないようです.

**Comment by sankichi92** [comment]
共演者の順序に関しては 157ed9b5b2c65cf1fcfbf8bb5de929581758d662 で改善しました。

**Comment by sankichi92** [comment]
@rhinocerosSai この Issue はクローズでいいですかね？

**Comment by rhinocerosSai** [comment]
表示に関して良い案を思いつかないので一旦クローズにしようとおもいます.
ありがとうございました.
