### ISSUE TITLE
曲の編集で演者を消して再度追加すると uniqueness バリデーションに引っかかってしまう

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#27]
`PG::UniqueViolation: ERROR: duplicate key value violates unique constraint` で落ちる。

**Comment by sankichi92** [comment]
デフォルトの順番は設定したが，フォームで演者の欄を入れ替えると依然エラーが出る

**Comment by rhinocerosSai** [comment]
playings の, (`user_id`, `song_id`) が unique のため,
例えば, 
1. playings に(`user_id`, `song_id`) = (1, 1),  (2, 1) というレコードが存在し, 入れ替えをすると,
1.  まず (1,1) のレコードを (2,1) にアップデートしようとする
1. 既に(2,1)というレコードが存在するため, UniqueValidation のエラーが出る

という流れでエラーが出ているようです.

アップデートしようとしている song を含んでいる playing のレコードを削除し, 作り直す, という流れがシンプルな解決策かと思います

**Comment by sankichi92** [comment]
あれ，久々にやってみると再現しなかった😕
@rhinocerosSai さんの方では再現できましたか……？

こないだ Rails のアップデートしたんだけど，その中に bug fix 含まれてたのかな……。

ただ，依然として1つの曲に同じメンバーを重複して登録しようとするとエラーで落ちるので，そこには適切なバリデーション設定しようと思います。
コメントありがとうございました！

**Comment by sankichi92** [comment]
再現しなかったので，いったんクローズします。

**Comment by sankichi92** [comment]
> あれ，久々にやってみると再現しなかった😕

複数人消したり追加したり色々してると再現しました。
順序によってはうまく更新できる場合もあるみたいですね……。

エラーで落ちることは無くなったものの，予期しないバリデーションエラーを吐くことになるので再度オープンにします。
現状は `@song.update_attributes(song_params)` 一発で更新するシンプルなコードになっていて，更新処理があまり複雑になるようならこのままでもいいかなと思っています。

**Comment by sankichi92** [comment]
いや，`uniqueness: { scope: :song_id }` 消したらちゃんと更新されたので，バリデーションが悪さしているみたいですね……。

#### バリデーションなしの場合

- 演者を一度消して再度追加 → きちんと更新される
- 1つの曲に演者を重複して追加 → `PG::UniqueViolation` で落ちる

#### バリデーションありの場合

- 演者を一度消して再度追加 → バリデーションが働いて更新されない
- 1つの曲に演者を重複して追加 → きちんとバリデーションが働く

予期せぬエラーで落ちるのが最悪なので，とりあえずバリデーションありのままにします。

**Comment by sankichi92** [comment]
#### 修正方針

`_destroy` フラグが立っているユーザーが再度追加されていたら `_destory` フラグを戻す

#### 具体的な実装方法

1. Save ボタンを押した時に JavaScript でやる？
2. `before_validation` コールバックでやる？
