### ISSUE TITLE
プロフィール画像を設定できるようにする

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#58]
Gravatar を使う

**Comment by rhinocerosSai** [comment]
画像を表示するのは
- navbar
- members/#{id}
- songs/#{id}

でしょうか?

**Comment by sankichi92** [comment]
全然考えてなかったんですが，それに加えて `/members` もかなと思います。
Bootstrap の Media object 使って表示するつもりでした。
https://getbootstrap.com/docs/4.0/layout/media-object/

**Comment by sankichi92** [comment]
asignee が設定されている…！
本音を言うと，Facebook 連携してそこから写真取ってきたいです。
Gravatar なんて普通使ってないですし。

**Comment by rhinocerosSai** [comment]
なるほど, Facebook ですか....
Facebook 用の登録など一括でされた方がトラブルがないかと思いますので, 一旦assignee をはずそうと思います.

**Comment by sankichi92** [comment]
あ，Facebook は理想形であって，Gravatar から始めるのは全然ありだと思ってます。
Google or Facebook 連携はできればやりたいですが，当分やることはなさそうです。

**Comment by rhinocerosSai** [comment]
ではひとまずGravatar から画像を取得する方法でやろうとおもいます

**Comment by sankichi92** [comment]
Rails 5.2 が出たら Active Strage でアップロードからリサイズ・表示まで簡単にできるようになりそう。
https://railsguides.jp/active_storage_overview.html

**Comment by sankichi92** [comment]
#259
