### ISSUE TITLE
entry 中の曲を不可視にする

### ISSUE THREAD

**Issue by rhinocerosSai** [sankichi92/LiveLog#94]
- クリスマスライブなど, 曲目を秘密としておきたいライブ
- entry 後の song 変更を気兼ねなく行う

ため, 未来のライブのページについては, 自分が関わっているライブ以外表示されないようにする

**Comment by sankichi92** [comment]
@rhinocerosSai さんの方でやるつもりだったら Assignees 設定してもらえると助かります🙏
僕がやってもいいようなら（やるかどうかは別として）そのままで大丈夫です。

**Comment by sankichi92** [comment]
現状，ライブ1週間前になると全ユーザーにセットリストが公開される仕様になっているんですが，これも微妙っぽいですね……。
ちなみに，Entry の機能を入れたのは，NF 期の管理者による曲入力（去年まで私がやってました）の負担を和らげたかったからです。
なので，NF 以外，特にクリスマスライブなんかは，従来通りメール等でやってもいいのでは，と個人的には思っています。

**Comment by sankichi92** [comment]
一週間前のリハで基本的に曲バレするから一週間前公開でいいかと適当に決めたんですが，セットリストってふつうライブに行って初めてわかるものなので，一週間前公開自体がそもそもおかしいですね……。
これ，当日公開に仕様変更します。

**Comment by sankichi92** [comment]
PR マージしていただいたようなので閉じますね。

PR の description やコミットメッセージに "Close #94" とか "Resolve #94" とか書いておくと，Issue が自動で閉じられて便利です。
cf. https://help.github.com/articles/closing-issues-using-keywords/
